title: Daniel Díaz Hacks
description: "Una página para hablar de programación competitiva, inteligencia artificial y software libre"
author:
  name: "Daniel Díaz Bedoya"
  email: "ddiazbedoya16@gmail.com"
  url: "https://danielteniente.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "DanDB"
year : "2021"
